# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push events but 
# only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

     # Copy the index.html file to the droplet at the correct directory
     - name: Copy index.html via scp (secure copy)
     uses: appleboy/scp-action@master
     env:
       HOST: ${{ secrets.HOST }} 
       USERNAME: ${{ secrets.USERNAME }} 
       PASSWORD: ${{ secrets.PASSWORD }}
       PORT: ${{ secrets.PORT }}
     with:
       source: "index.html"
       target: "/var/www/digitalagconsultants.com"

   # Copy all the nodejs sources to the droplet servlet directory
   - name: Copy node_src via scp (secure copy)
     uses: appleboy/scp-action@master
     env:
       HOST: ${{ secrets.HOST }} 
       USERNAME: ${{ secrets.USERNAME }} 
       PASSWORD: ${{ secrets.PASSWORD }}
       PORT: ${{ secrets.PORT }}
     with:
       source: "node/server.js"
       target: "/apps/nodejs"
       strip_components: 1 # Remove the folder level above server.js

       